// Mock data for demo/preview mode (no DB required)

export const mockServices = [
  {
    id: "svc-1",
    name: "Nginx Proxy",
    description: "Main reverse proxy for all services",
    url: "https://proxy.homelab.local",
    type: "HTTPS",
    category: "Web",
    tags: ["proxy", "web", "critical"],
    nodeId: "node-1",
    node: { id: "node-1", name: "Dell R920", type: "PHYSICAL" },
    port: 443,
    icon: "🌐",
    color: "#3B82F6",
    isActive: true,
    isPinned: true,
    pingEnabled: true,
    pingInterval: 30,
    pingTimeout: 10,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "UP",
    lastCheckedAt: new Date(Date.now() - 45000).toISOString(),
    lastUpAt: new Date(Date.now() - 45000).toISOString(),
    lastDownAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    _uptimePercent: 99.97,
    _responseTime: 12,
  },
  {
    id: "svc-2",
    name: "PostgreSQL",
    description: "Primary database server",
    url: "tcp://db.homelab.local:5432",
    type: "TCP",
    category: "Database",
    tags: ["database", "critical"],
    nodeId: "node-1",
    node: { id: "node-1", name: "Dell R920", type: "PHYSICAL" },
    port: 5432,
    icon: "🐘",
    color: "#336791",
    isActive: true,
    isPinned: true,
    pingEnabled: true,
    pingInterval: 30,
    pingTimeout: 5,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "UP",
    lastCheckedAt: new Date(Date.now() - 30000).toISOString(),
    lastUpAt: new Date(Date.now() - 30000).toISOString(),
    lastDownAt: null,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    _uptimePercent: 100,
    _responseTime: 3,
  },
  {
    id: "svc-3",
    name: "Grafana",
    description: "Monitoring and observability dashboards",
    url: "http://grafana.homelab.local:3000",
    type: "HTTP",
    category: "Monitoring",
    tags: ["monitoring", "dashboards"],
    nodeId: "node-1",
    node: { id: "node-1", name: "Dell R920", type: "PHYSICAL" },
    port: 3000,
    icon: "📊",
    color: "#F46800",
    isActive: true,
    isPinned: false,
    pingEnabled: true,
    pingInterval: 60,
    pingTimeout: 10,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "DEGRADED",
    lastCheckedAt: new Date(Date.now() - 60000).toISOString(),
    lastUpAt: new Date(Date.now() - 300000).toISOString(),
    lastDownAt: new Date(Date.now() - 60000).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 600000).toISOString(),
    _uptimePercent: 98.5,
    _responseTime: 892,
  },
  {
    id: "svc-4",
    name: "Nextcloud",
    description: "Self-hosted file sync and share",
    url: "https://cloud.homelab.local",
    type: "HTTPS",
    category: "Web",
    tags: ["files", "sync", "cloud"],
    nodeId: "node-2",
    node: { id: "node-2", name: "Proxmox VM-101", type: "VIRTUAL" },
    port: 443,
    icon: "☁️",
    color: "#0082C9",
    isActive: true,
    isPinned: false,
    pingEnabled: true,
    pingInterval: 60,
    pingTimeout: 15,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "UP",
    lastCheckedAt: new Date(Date.now() - 55000).toISOString(),
    lastUpAt: new Date(Date.now() - 55000).toISOString(),
    lastDownAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    _uptimePercent: 99.8,
    _responseTime: 245,
  },
  {
    id: "svc-5",
    name: "Home Assistant",
    description: "Home automation platform",
    url: "http://ha.homelab.local:8123",
    type: "HTTP",
    category: "Automation",
    tags: ["iot", "automation", "smart-home"],
    nodeId: "node-2",
    node: { id: "node-2", name: "Proxmox VM-101", type: "VIRTUAL" },
    port: 8123,
    icon: "🏠",
    color: "#41BDF5",
    isActive: true,
    isPinned: true,
    pingEnabled: true,
    pingInterval: 30,
    pingTimeout: 10,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "UP",
    lastCheckedAt: new Date(Date.now() - 25000).toISOString(),
    lastUpAt: new Date(Date.now() - 25000).toISOString(),
    lastDownAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 28).toISOString(),
    updatedAt: new Date(Date.now() - 900000).toISOString(),
    _uptimePercent: 99.95,
    _responseTime: 67,
  },
  {
    id: "svc-6",
    name: "Plex Media Server",
    description: "Media streaming server",
    url: "http://plex.homelab.local:32400",
    type: "HTTP",
    category: "Media",
    tags: ["media", "streaming", "entertainment"],
    nodeId: "node-1",
    node: { id: "node-1", name: "Dell R920", type: "PHYSICAL" },
    port: 32400,
    icon: "🎬",
    color: "#E5A00D",
    isActive: true,
    isPinned: false,
    pingEnabled: true,
    pingInterval: 60,
    pingTimeout: 10,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "DOWN",
    lastCheckedAt: new Date(Date.now() - 120000).toISOString(),
    lastUpAt: new Date(Date.now() - 3600000).toISOString(),
    lastDownAt: new Date(Date.now() - 120000).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 120000).toISOString(),
    _uptimePercent: 95.2,
    _responseTime: 0,
  },
  {
    id: "svc-7",
    name: "Redis Cache",
    description: "In-memory cache and message broker",
    url: "tcp://redis.homelab.local:6379",
    type: "TCP",
    category: "Database",
    tags: ["cache", "redis"],
    nodeId: "node-1",
    node: { id: "node-1", name: "Dell R920", type: "PHYSICAL" },
    port: 6379,
    icon: "⚡",
    color: "#DC382D",
    isActive: true,
    isPinned: false,
    pingEnabled: true,
    pingInterval: 30,
    pingTimeout: 5,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "UP",
    lastCheckedAt: new Date(Date.now() - 20000).toISOString(),
    lastUpAt: new Date(Date.now() - 20000).toISOString(),
    lastDownAt: null,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 5000).toISOString(),
    _uptimePercent: 100,
    _responseTime: 1,
  },
  {
    id: "svc-8",
    name: "Wireguard VPN",
    description: "VPN tunnel endpoint",
    url: "10.0.0.1",
    type: "PING",
    category: "Network",
    tags: ["vpn", "network", "security"],
    nodeId: "node-1",
    node: { id: "node-1", name: "Dell R920", type: "PHYSICAL" },
    port: 51820,
    icon: "🔒",
    color: "#88171A",
    isActive: true,
    isPinned: false,
    pingEnabled: true,
    pingInterval: 60,
    pingTimeout: 5,
    expectedStatus: 200,
    pingMethod: "GET",
    currentStatus: "UP",
    lastCheckedAt: new Date(Date.now() - 50000).toISOString(),
    lastUpAt: new Date(Date.now() - 50000).toISOString(),
    lastDownAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 50000).toISOString(),
    _uptimePercent: 99.99,
    _responseTime: 8,
  },
]

const levels = ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"] as const
const logMessages = [
  { level: "INFO", message: "Service health check passed", source: "ping-worker" },
  { level: "INFO", message: "User logged in successfully", source: "auth.ts" },
  { level: "INFO", message: "Database connection pool initialized (size: 10)", source: "prisma.ts" },
  { level: "WARN", message: "Response time exceeded 500ms threshold", source: "ping-worker" },
  { level: "WARN", message: "Redis connection retry attempt 2/10", source: "redis.ts" },
  { level: "WARN", message: "Rate limit approaching for ingestion endpoint", source: "ingest/logs" },
  { level: "ERROR", message: "Connection refused: ECONNREFUSED 10.0.0.5:32400", source: "ping-worker" },
  { level: "ERROR", message: "Failed to send Discord notification: 429 Too Many Requests", source: "alerts.ts" },
  { level: "ERROR", message: "SSL certificate expires in 3 days for cloud.homelab.local", source: "cert-check" },
  { level: "DEBUG", message: "Processing uptime check job: svc-1", source: "ping-worker" },
  { level: "DEBUG", message: "Cache HIT for license status", source: "license.ts" },
  { level: "INFO", message: "Alert cooldown reset for 'Plex Down'", source: "alert-worker" },
  { level: "INFO", message: "Cleanup worker removed 1,247 old log entries", source: "cleanup-worker" },
  { level: "ERROR", message: "Grafana health check returned HTTP 503", source: "ping-worker" },
  { level: "WARN", message: "Disk usage at 82% on node Dell R920", source: "metrics" },
  { level: "INFO", message: "Metric ingestion: 24 points received for svc-2", source: "ingest/metrics" },
  { level: "FATAL", message: "Out of memory: JavaScript heap allocation failed", source: "plex-monitor" },
  { level: "INFO", message: "Dashboard layout saved for user admin", source: "dashboard" },
  { level: "WARN", message: "Service 'Grafana' status changed: UP → DEGRADED", source: "ping-worker" },
  { level: "ERROR", message: "Webhook delivery failed: timeout after 10000ms", source: "alerts.ts" },
]

export function generateMockLogs(count: number = 50) {
  return Array.from({ length: count }, (_, i) => {
    const template = logMessages[i % logMessages.length]
    const serviceIndex = Math.floor(Math.random() * mockServices.length)
    return {
      id: `log-${i + 1}`,
      serviceId: mockServices[serviceIndex].id,
      service: { id: mockServices[serviceIndex].id, name: mockServices[serviceIndex].name },
      level: template.level,
      message: template.message,
      source: template.source,
      metadata: template.level === "ERROR" ? { stack: "at processCheck (/app/src/workers/pingWorker.ts:45:12)", retries: 3 } : null,
      timestamp: new Date(Date.now() - i * 47000).toISOString(),
    }
  })
}

export function generateUptimeChecks(serviceId: string, hours: number = 24) {
  const checks = []
  for (let i = 0; i < hours * 2; i++) {
    const isDown = serviceId === "svc-6" && i < 4
    const isDegraded = serviceId === "svc-3" && i % 8 === 0
    checks.push({
      id: `check-${serviceId}-${i}`,
      serviceId,
      status: isDown ? "DOWN" : isDegraded ? "DEGRADED" : "UP",
      responseTime: isDown ? null : Math.floor(Math.random() * 200) + 5,
      statusCode: isDown ? null : 200,
      error: isDown ? "ECONNREFUSED" : null,
      checkedAt: new Date(Date.now() - i * 1800000).toISOString(),
    })
  }
  return checks
}

export const mockAlerts = [
  {
    id: "alert-1",
    name: "Plex Server Down",
    serviceId: "svc-6",
    service: { id: "svc-6", name: "Plex Media Server" },
    type: "SERVICE_DOWN",
    condition: { field: "status", operator: "eq", value: "DOWN" },
    severity: "CRITICAL",
    isEnabled: true,
    cooldownMins: 15,
    lastFiredAt: new Date(Date.now() - 120000).toISOString(),
    events: [
      { id: "evt-1", alertId: "alert-1", message: "Plex Media Server is DOWN — ECONNREFUSED", firedAt: new Date(Date.now() - 120000).toISOString(), resolvedAt: null, metadata: null },
      { id: "evt-2", alertId: "alert-1", message: "Plex Media Server is DOWN — timeout", firedAt: new Date(Date.now() - 86400000 * 3).toISOString(), resolvedAt: new Date(Date.now() - 86400000 * 3 + 600000).toISOString(), metadata: null },
    ],
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "alert-2",
    name: "Grafana Slow Response",
    serviceId: "svc-3",
    service: { id: "svc-3", name: "Grafana" },
    type: "SERVICE_SLOW",
    condition: { field: "responseTime", operator: "gt", value: 500 },
    severity: "WARNING",
    isEnabled: true,
    cooldownMins: 30,
    lastFiredAt: new Date(Date.now() - 3600000).toISOString(),
    events: [
      { id: "evt-3", alertId: "alert-2", message: "Grafana response time 892ms exceeds 500ms threshold", firedAt: new Date(Date.now() - 3600000).toISOString(), resolvedAt: null, metadata: null },
    ],
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "alert-3",
    name: "High Error Rate",
    serviceId: null,
    service: null,
    type: "HIGH_ERROR_RATE",
    condition: { field: "errorRate", operator: "gt", value: 5, windowMins: 15 },
    severity: "WARNING",
    isEnabled: true,
    cooldownMins: 60,
    lastFiredAt: new Date(Date.now() - 86400000).toISOString(),
    events: [
      { id: "evt-4", alertId: "alert-3", message: "Error rate 6.2% exceeds 5% threshold in last 15 minutes", firedAt: new Date(Date.now() - 86400000).toISOString(), resolvedAt: new Date(Date.now() - 86400000 + 1200000).toISOString(), metadata: null },
    ],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
]

export const mockNodes = [
  {
    id: "node-1",
    name: "Dell R920",
    description: "Primary server — 4x E7-4870 v2, 512GB DDR3",
    type: "PHYSICAL",
    hostname: "r920.homelab.local",
    ipAddress: "10.0.0.2",
    os: "Proxmox VE 8.1",
    cpu: "4x Intel Xeon E7-4870 v2 (60 cores)",
    ram: "512 GB DDR3 ECC",
    storage: "8x 1.2TB SAS (RAID-6)",
    tags: ["primary", "proxmox"],
    isActive: true,
    _serviceCount: 5,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "node-2",
    name: "Proxmox VM-101",
    description: "Application VM running Docker containers",
    type: "VIRTUAL",
    hostname: "vm101.homelab.local",
    ipAddress: "10.0.0.10",
    os: "Ubuntu 24.04 LTS",
    cpu: "8 vCPU",
    ram: "32 GB",
    storage: "500 GB NVMe",
    tags: ["docker", "apps"],
    isActive: true,
    _serviceCount: 3,
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
]

export function generateAnalytics() {
  const hours = 24
  const uptimeTrend = Array.from({ length: hours }, (_, i) => ({
    time: new Date(Date.now() - (hours - i) * 3600000).toISOString(),
    uptime: 95 + Math.random() * 5,
  }))
  const responseTimeTrend = Array.from({ length: hours }, (_, i) => ({
    time: new Date(Date.now() - (hours - i) * 3600000).toISOString(),
    p50: 40 + Math.random() * 60,
    p95: 150 + Math.random() * 200,
    p99: 300 + Math.random() * 500,
  }))
  const logVolumeTrend = Array.from({ length: hours }, (_, i) => ({
    time: new Date(Date.now() - (hours - i) * 3600000).toISOString(),
    DEBUG: Math.floor(Math.random() * 20),
    INFO: Math.floor(Math.random() * 150) + 50,
    WARN: Math.floor(Math.random() * 30) + 5,
    ERROR: Math.floor(Math.random() * 15),
    FATAL: Math.random() > 0.9 ? 1 : 0,
  }))

  return {
    totalServices: 8,
    servicesUp: 6,
    servicesDown: 1,
    servicesDegraded: 1,
    avgUptime: 99.2,
    totalLogs: 45231,
    errorRate: 3.1,
    avgResponseTime: 187,
    totalChecks: 12480,
    activeAlerts: 2,
    slowestService: { id: "svc-3", name: "Grafana", avgResponseTime: 892 },
    mostErrors: { id: "svc-6", name: "Plex Media Server", errorCount: 142 },
    uptimeTrend,
    responseTimeTrend,
    logVolumeTrend,
  }
}

export function generateUptimeSummary() {
  return {
    services: mockServices.map((s) => ({
      id: s.id,
      name: s.name,
      uptimePercent: s._uptimePercent,
      avgResponseTime: s._responseTime,
      checksTotal: 1440,
      checksUp: Math.floor(1440 * (s._uptimePercent / 100)),
      currentStatus: s.currentStatus,
    })),
  }
}

export const mockLicenseStatus = {
  plan: "FREE" as const,
  isValid: false,
  features: {
    maxServices: 5,
    maxAlerts: 3,
    maxNodes: 1,
    logRetentionDays: 3,
    uptimeRetentionDays: 7,
    pingIntervalMin: 60,
    maxLogIngestionPerMin: 100,
    dashboardWidgets: 6,
    multiDashboard: false,
    advancedAnalytics: false,
    customWidgets: false,
    apiAccess: false,
    webhookAlerts: false,
    discordAlerts: false,
    slackAlerts: false,
    exportData: false,
    nodeTracking: false,
    metricIngestion: false,
    customPingHeaders: false,
    tcpMonitoring: false,
    dnsMonitoring: false,
  },
}
